In [ ]:
import tensorflow as tf
import numpy as np

sess = tf.Session()
def run(op):
    return sess.run(op)

In [ ]:
tfzer = tf.zeros([3,4])
run(tf.transpose(tfzer))

In [ ]:
tf_fill = tf.fill([3,3], value=32)
tf_fill = tf.cast(tf_fill, tf.float32)
tfone = tf.ones([3,4], dtype=tf.float32)

In [ ]:
# print(sess.run(tf_fill))
A,B = tfone, tf_fill 
# print(sess.run(tf.matmul(A,B)))


In [ ]:
tf_cons = tf.constant([1,2,3,4,5])

In [ ]:
tf_cons1 = tf.constant(3, shape=[3,4])

In [ ]:
zero_simi = tf.zeros_like(tfzer)
one_simi = tf.ones_like(tfone)
run(one_simi)

In [ ]:
# random_tf = tf.random_uniform([2,3,4], minval=0, maxval=1)
# sess = tf.Session()
# print(tf.run(random_tf))

In [ ]:
sess = tf.Session()
a = tf.truncated_normal([2,3])
run(a)
print()
b = tf.zeros([2,3])
run(b)
print()
c = tf.ones([2,3])
run(c)
print()
d = tf.random_uniform([3,3], minval=0, maxval=2)
# run(d)
run(tf.matrix_determinant(d))

In [ ]:
e = tf.convert_to_tensor(np.array([1,2,3,4,3,2,3,4,5,5]), dtype=tf.float32)
print(sess.run(e))

In [ ]:
run(tf.matrix_determinant(tf_fill))

### PERKALIAN

In [ ]:
run(tf.multiply(10,4))

### PEMBAGIAN

In [ ]:
run(tf.div(10,4))

### PENJUMLAHAN

In [ ]:
run(tf.add(10,4))

### PENGURANGAN

In [118]:
run(tf.subtract(10,4))
run(tf.mod(10,4))

In [119]:
c = tf.cross(np.random.rand(10).reshape(1,10), np.random.rand(10).reshape(1,10))
run(c)

array([-1,  1, -1])

In [129]:
def kostum_poly(value):
    return run(tf.subtract(tf.square(value), value) + 10)

In [132]:
kostum_poly(10)

100

## ACTIVATION FUNCTION

In [161]:
arrayku = [1,3,-2, 10]
def activation_function_list(arr):
    a = tf.constant(arr)
    a = tf.cast(a, dtype=tf.float32)

    a1 = tf.nn.sigmoid(a)
    a2 = tf.nn.tanh(a)
    a3 = tf.nn.relu(a)
    a4 = tf.nn.relu6(a)
    a5 = tf.nn.softsign(a)
    a6 = tf.nn.softplus(a)
    a7 = tf.nn.elu(a)
    list_af = {
        'sig':a1,
        'tanh':a2,
        'relu':a3,
        'relu6':a4,
        'softsign':a5,
        'softplus':a6,
        'elu':a7
    }
    return list_af

In [166]:
run(activation_function_list(arrayku)['elu'])

array([ 1.        ,  3.        , -0.86466473, 10.        ], dtype=float32)

## WORKING WITH DATA SOURCE

In [167]:
from sklearn import datasets

In [182]:
iris = datasets.load_iris()
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [187]:
from tensorflow.examples.tutorials.mnist import input_data
import matplotlib.pyplot as plt

In [ ]:
mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)

In [218]:
len(mnist.train.images)
len(mnist.test.images)
train = mnist.train.images
train = train.reshape(55000, 28,28,1)

In [216]:
28**2

784

In [ ]:
# plt.figure(figsize=[10,15])
# plt.subplot(1,1,1)
plt.imshow(train[0])
train[0].shape